### ISSUE TITLE
Website rendering is incorrect

### ISSUE THREAD

**Issue by AshishBora** [sagarjha/multi-run#2]
Macbook Pro, 13 inch, OSX El Capitan 10.11.5
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

100% and 80% zooms: https://imgur.com/a/hrxkH0O

**Comment by sagarjha** [comment]
Thanks a lot for pointing out! I had given some attention to rendering on my phone screen before, but I missed specifying the margin for bigger screens. Let me know if the issue is fixed.

**Comment by AshishBora** [comment]
Its fixed now! :)
